name: Deploy to neocities

# only run on changes to main. Use main or master depending on whatever your default branch is called.
on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # Set up any tools and build steps here
    # This example uses a Node.js toolchain to build a site  
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v2.0.2
      with:
        api_token: d23b4f19e3df4c19d97735f536035d74
        cleanup: false
        dist_dir: public



        